### ISSUE TITLE
cofused

### ISSUE THREAD

**Issue by simaniu** [object-tracking-thesis/kitti-conv-vis#1]
i just feel confused. i cannot find the file kitti2pcd.cpp.

**Comment by mleue** [comment]
Hey simaniu, sry for the late reply. This project was quite a while back and I didn't really remember either. I now checked and this project only contains the already-compiled bin file for `kitti2pcd`. It calls it in `convert.sh` to convert kitti files to .pcd if one so wishes. Those .pcd files can then be visualized with the code in this repo.

I think I took the `kitti2pcd` code from https://github.com/yanii/kitti-pcl/tree/master/src and compiled it.

Hope that helps.
